export const RealtimeEvents = {
  // Order Events
  NEW_ORDER: "NEW_ORDER",
  ORDER_ACCEPTED: "ORDER_ACCEPTED",
  ORDER_REJECTED: "ORDER_REJECTED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_PREPARING: "ORDER_PREPARING",
  ORDER_PREPARATION_TIME_UPDATED: "ORDER_PREPARATION_TIME_UPDATED",
  ORDER_READY: "ORDER_READY",
  ORDER_PICKED_UP: "ORDER_PICKED_UP",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_COMPLETED: "ORDER_COMPLETED",

  // Vendor Events
  VENDOR_ONLINE: "VENDOR_ONLINE",
  VENDOR_OFFLINE: "VENDOR_OFFLINE",
  VENDOR_OPENED: "VENDOR_OPENED",
  VENDOR_CLOSED: "VENDOR_CLOSED",
  MENU_UPDATED: "MENU_UPDATED",
  MEAL_ADDED: "MEAL_ADDED",
  MEAL_UPDATED: "MEAL_UPDATED",
  MEAL_REMOVED: "MEAL_REMOVED",
  MEAL_OUT_OF_STOCK: "MEAL_OUT_OF_STOCK",
  MEAL_BACK_IN_STOCK: "MEAL_BACK_IN_STOCK",
  QUEUE_UPDATED: "QUEUE_UPDATED",
  DEMAND_UPDATED: "DEMAND_UPDATED",
  ESTIMATED_WAIT_UPDATED: "ESTIMATED_WAIT_UPDATED",
  BALANCE_UPDATED: "BALANCE_UPDATED",
  SETTLEMENT_COMPLETED: "SETTLEMENT_COMPLETED",

  // Customer Events
  CUSTOMER_CONNECTED: "CUSTOMER_CONNECTED",
  CUSTOMER_DISCONNECTED: "CUSTOMER_DISCONNECTED",
  CUSTOMER_LOCATION_UPDATED: "CUSTOMER_LOCATION_UPDATED",
  CUSTOMER_ORDER_VIEWING: "CUSTOMER_ORDER_VIEWING",

  // Trekker Events
  TREKKER_ONLINE: "TREKKER_ONLINE",
  TREKKER_OFFLINE: "TREKKER_OFFLINE",
  TREKKER_LOCATION_UPDATED: "TREKKER_LOCATION_UPDATED",
  TREKKER_ASSIGNED: "TREKKER_ASSIGNED",
  TREKKER_ACCEPTED: "TREKKER_ACCEPTED",
  TREKKER_REJECTED: "TREKKER_REJECTED",
  TREKKER_ARRIVED_VENDOR: "TREKKER_ARRIVED_VENDOR",
  TREKKER_PICKED_UP: "TREKKER_PICKED_UP",
  TREKKER_NEAR_CUSTOMER: "TREKKER_NEAR_CUSTOMER",
  TREKKER_DELIVERED: "TREKKER_DELIVERED",

  // Admin Events
  NEW_VENDOR_REGISTERED: "NEW_VENDOR_REGISTERED",
  VENDOR_APPROVED: "VENDOR_APPROVED",
  VENDOR_SUSPENDED: "VENDOR_SUSPENDED",
  NEW_TREKKER_REGISTERED: "NEW_TREKKER_REGISTERED",
  TREKKER_APPROVED: "TREKKER_APPROVED",
  SYSTEM_NOTIFICATION: "SYSTEM_NOTIFICATION",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",

  // Payment Events
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYOUT_PROCESSING: "PAYOUT_PROCESSING",
  PAYOUT_COMPLETED: "PAYOUT_COMPLETED",

  // Notification Events
  PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
  IN_APP_NOTIFICATION: "IN_APP_NOTIFICATION",
  EMAIL_NOTIFICATION: "EMAIL_NOTIFICATION",
  SMS_NOTIFICATION: "SMS_NOTIFICATION",

  // Chat Events
  CHAT_MESSAGE_SENT: "CHAT_MESSAGE_SENT",
  CHAT_MESSAGE_RECEIVED: "CHAT_MESSAGE_RECEIVED",
  CHAT_TYPING: "CHAT_TYPING",
  CHAT_READ: "CHAT_READ",

  // Queue Events
  QUEUE_JOINED: "QUEUE_JOINED",
  QUEUE_LEFT: "QUEUE_LEFT",
  QUEUE_POSITION_UPDATED: "QUEUE_POSITION_UPDATED",
  QUEUE_ESTIMATED_TIME_UPDATED: "QUEUE_ESTIMATED_TIME_UPDATED",

  // Demand Events
  DEMAND_LOW: "DEMAND_LOW",
  DEMAND_MODERATE: "DEMAND_MODERATE",
  DEMAND_HIGH: "DEMAND_HIGH",
  DEMAND_CRITICAL: "DEMAND_CRITICAL",

  // Analytics Events
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_FINISHED: "ORDER_FINISHED",
  CUSTOMER_RETURNED: "CUSTOMER_RETURNED",
  NEW_CUSTOMER: "NEW_CUSTOMER",
  POPULAR_MEAL_UPDATED: "POPULAR_MEAL_UPDATED",
  POPULAR_VENDOR_UPDATED: "POPULAR_VENDOR_UPDATED",

  // Presence
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  USER_IDLE: "USER_IDLE",
  USER_ACTIVE: "USER_ACTIVE",
} as const;

export type RealtimeEvent = keyof typeof RealtimeEvents;
